server:
  port: 8089
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/NormalLibraryDatabase4
  application:
    name: UserClient

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

